dataBaseParam: useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
#上传文件配置
virtualPath: '/file/'
uploadPath: 'd:/uploadPath/'
#uploadPath: '/Users/mshe/developer/uploadPath'
# 设置最大文件大小
spring.servlet.multipart.max-file-size: 100MB
# 设置最大请求大小
spring.servlet.multipart.max-request-size: 100MB
###
server.port: 9093
server.application.name: learn

spring.profiles.active: dev

mybatis-plus.mapper-locations: classpath*:mapper/*.xml,classpath*:cn/crabapples/system/**/dao/mybatis/xml/*.xml
logging.file.name: logs/springboot-jwt/
#出现错误时, 直接抛出异常
#spring.mvc.throw-exception-if-no-handler-found: true
#不要为我们工程中的资源文件建立映射
#spring.web.resources.add-mappings: false

### turingApi config ###
crabapples.turing.url: http://openapi.tuling123.com/openapi/api/v2
crabapples.turing.appKey: 67e51f0bc2864cdc8256f24dadf218f8




